### ISSUE TITLE
Only 1 a in Pardiso?

### ISSUE THREAD

**Issue by tkelman** [KristofferC/Pardiso.jl#1]
Is https://github.com/KristofferC/Pardiso.jl/blob/6658e7a6f47678fc977c799b62417babc43b7dd9/src/Pardiso.jl#L16 a typo, or is the .so you have actually called that?

**Comment by KristofferC** [comment]
It is a typo but I made the same typo when I renamed my .so file hehe.

I fixed it now I hope.

Many thanks.

**Comment by tkelman** [comment]
ah thought that might've been what happened

closed by d13438e48f8bf5945d06c47067bc00b1a3be7824
