### ISSUE TITLE
add package problem 

### ISSUE THREAD

**Issue by userchba** [KristofferC/Pardiso.jl#101]
when I add  any package, this issue will occur, but at fist time of installing julia, I can add the package. I don't know the reason. I have tried to delete the julia(~/.julia) and reinstall the julia, but the issue is still here. Appreciate it if there is anyone can give a helping hand.
(@v1.6) pkg> add Pardiso
    Updating registry at `~/.julia/registries/General`
┌ Error: curl_multi_socket_action: 8
└ @ Downloads.Curl /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/Downloads/src/Curl/utils.jl:36

**Comment by KristofferC** [comment]
This is not an issue with this package in particular. I've seen people run into this when interrupting a download but restarting julia fixed it then. Anyway, nothing that can be fixed here.
