### ISSUE TITLE
having error while running Pkg.build("Pardiso")

### ISSUE THREAD

**Issue by chegini** [KristofferC/Pardiso.jl#13]
Hi,
I have the following error while I run Pkg.build("Pardiso")**, could you please tell me how to fix the problem.

**julia> Pkg.update()**
INFO: Updating METADATA...
INFO: Updating cache of FixedPointNumbers...
INFO: Computing changes...
INFO: Upgrading FixedPointNumbers: v0.1.5 => v0.1.6

**julia> Pkg.add("Pardiso")**
INFO: Nothing to be done

**julia> Pkg.build("Pardiso")**
INFO: Building Pardiso
WARNING: `@unix_only` is deprecated, use `@static if is_unix()` instead
 in depwarn(::String, ::Symbol) at ./deprecated.jl:64
 in depwarn(::String, ::Symbol) at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 in @unix_only(::Any) at ./deprecated.jl:493
 in include_from_node1(::String) at ./loading.jl:426
 in include_from_node1(::String) at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 in evalfile(::String, ::Array{String,1}) at ./loading.jl:442 (repeats 2 times)
 in cd(::##2#4, ::String) at ./file.jl:59
 in (::##1#3)(::IOStream) at ./none:13
 in open(::##1#3, ::String, ::String) at ./iostream.jl:113
 in eval(::Module, ::Any) at ./boot.jl:234
 in eval(::Module, ::Any) at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 in process_options(::Base.JLOptions) at ./client.jl:239
 in _start() at ./client.jl:318
 in _start() at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
while loading /Users/fatimachegini/.julia/v0.5/Pardiso/deps/build.jl, in expression starting on line 4
did not find libpardiso, assuming PARDISO 5.0 is not installed
did not find MKLROOT key, assuming MKL is not installed
WARNING: no Pardiso library managed to load

**Comment by KristofferC** [comment]
First, are you on Windows or Linux/MacOS? 

Secondly, are you trying to install the MKL Pardiso version or the one from http://www.pardiso-project.org/?

If the MKL version, have you set the `MKLROOT` variable like the README says: https://github.com/JuliaSparse/Pardiso.jl#mkl-pardiso

If the other version, where have you put the library file?

**Comment by chegini** [comment]
Thanks for the quick reply,
I am woking on MacOS. I use this framework 
https://github.com/JuliaSparse/Pardiso.jl/

I didn't install MKL paradiso. On MacOS we can use the flag: -framework Accelerate
here: **const MKLROOT= R"-framework Accelerate"**
 I am trying to install  http://www.pardiso-project.org/
For linking with the BLAS,  I used **is_apple()** in build.jl as follows:
**@static if is_apple() begin
    const LIBPARDISONAMES = [ "libpardiso500-MACOS-X86-64.dylib" ]
end**

**but I have this error:** 
fatimas-MacBook-Pro-2:test fatimachegini$ **julia runtests.jl** 
WARNING: `@windows_only` is deprecated, use `@static if is_windows()` instead
 in depwarn(::String, ::Symbol) at ./deprecated.jl:64
 in depwarn(::String, ::Symbol) at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 in @windows_only(::Any) at ./deprecated.jl:489
 in include_from_node1(::String) at ./loading.jl:426
 in include_from_node1(::String) at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 in eval(::Module, ::Any) at ./boot.jl:234
 in eval(::Module, ::Any) at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 in require(::Symbol) at ./loading.jl:357
 in require(::Symbol) at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 in include_from_node1(::String) at ./loading.jl:426
 in include_from_node1(::String) at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 in process_options(::Base.JLOptions) at ./client.jl:262
 in _start() at ./client.jl:318
 in _start() at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
while loading /Users/fatimachegini/.julia/v0.5/Pardiso/src/Pardiso.jl, in expression starting on line 52
WARNING: No Pardiso library found when Pkg.build("Pardiso") ran, this package will not currently be usable. Please see the installation instructions and rerun Pkg.build("Pardiso").
Testing DataType[]
ERROR: LoadError: No Pardiso library managed to load. Unable to run tests.
 in error(::String) at ./error.jl:21
 in error(::String) at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 in include_from_node1(::String) at ./loading.jl:426
 in include_from_node1(::String) at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
 in process_options(::Base.JLOptions) at ./client.jl:262
 in _start() at ./client.jl:318
 in _start() at /Applications/Julia-0.5.app/Contents/Resources/julia/lib/julia/sys.dylib:?
while loading /Users/fatimachegini/Dropbox/Lyra/Julia_Test/Pardiso.jl-master/test/runtests.jl, in expression starting on line 22
fatimas-MacBook-Pro-2:test fatimachegini$  

Therefore, when I run Pkg.build("Pardiso"), I have problem as I mentioned before.

**Comment by KristofferC** [comment]
So one of the problems seems to be that I have not added the `libpardiso500-MACOS-X86-64.dylib` file to `deps.jl` but if I understand correctly you added:

```
@static if is_apple() begin
    const LIBPARDISONAMES = [ "libpardiso500-MACOS-X86-64.dylib" ]
end
```

to the `deps.jl` file?

In that case, did you put the `.dylib` file inside the `deps` folder? What happens if you try to run `Libdl.dlopen(path, Libdl.RTLD_GLOBAL)` where `path` is the path to the `dylib` file?
