### ISSUE TITLE
Cannot build Pardiso on Windows 10. Perhaps because I have AMD chip?

### ISSUE THREAD

**Issue by donboyd5** [KristofferC/Pardiso.jl#20]
Hi. I am a brand new Julia user. I am investigating it because I have a very large scale NLP problem that I want to solve (3.5e6 variables, 70e3 linear constraints, 30e6 nonzero constraint coefficients). I thought combination of Ipopt and Pardiso, in Julia, might let me solve it. (The Ipopt default linear solver, Mumps, seems to hang up when I scale my problem up to full size.) However, have not figured out if I can use Pardiso.

System: Windows 10 Professional 64-bit, with AMD 8-core chip, 32gb RAM. Have obtained libpardiso500-WIN-X86-64.dll and academic license. (Perhaps the problem is that Pardiso won't run on AMD chip?)

Have successfully installed Ipopt package in Julia. Installed Pardiso package. Tried to build Pardiso package but get error: "did not find libpardiso, assuming PARDISO 5.0 is not installed". Have verified that Julia can find the Pardiso dll, with isfile(path) where path is path of the dll. Tried to load it with Libdl.dlopen(path, Libdl.RTLD_GLOBAL) but get the error: "could not load library [my path] The operation completed successfully. in dlopen(::String, ::UInt32) at libdl.jl:90"

So I suspect that my problem is the dll itself, but I hold out hope that there might be a solution because the Julia Pardiso package documentation does not say that I must have an Intel chip.

With that as background, would you mind telling me:
- do  you believe this is correct - the Pardiso dll will not work on an AMD chip?
- if so, do you know of any other options for running Pardiso in Julia on AMD chip?
- any other advice?

Many thanks in advance!

**Comment by KristofferC** [comment]
I did the following on Windows 10:

* Downloaded libpardiso500-WIN-X86-64.tgz.
* Unzipped to the deps directory in the Pardiso folder
* Ran `Pkg.build("Pardiso")`
* Everything seemed to work.

Now, I am not sure if the problem is the AMD chip or something else... You could perhaps try to install MKL and use the `MKLPardisoSolver` instead?

**Comment by donboyd5** [comment]
Many thanks. This was helpful. I am trying to track it down. Research suggests AMD should work. Turns out I did not have pardiso.lic installed in my Windows home directory. I have since done that. Still does not work but I think I gave the Pardiso folks a bad Windows username. I have applied for a new license and will try. Will report back.

**Comment by KristofferC** [comment]
If you don't have a valid license file you get:

```
***************************************************************************
CONTAINS Runtime Modules of Parallel Sparse Linear Solver PARDISO Vers. 5.0
Copyright Universita della Svizzera Italiana 2000-2014 All Rights Reserved.

No PARDISO license file found.  Please see `http://www.pardiso-project.org
where to place the license file pardiso.lic
***************************************************************************
ERROR: No license file pardiso.lic found.
Stacktrace:
 [1] check_error(::Pardiso.PardisoSolver, ::Int32) at C:\Users\KristofferC\.julia\v0.6\Pardiso\src\project_pardiso.jl:188
 [2] pardisoinit(::Pardiso.PardisoSolver) at C:\Users\KristofferC\.julia\v0.6\Pardiso\src\Pardiso.jl:167
 [3] solve!(::Pardiso.PardisoSolver, ::Array{Float64,1}, ::SparseMatrixCSC{Float64,Int64}, ::Array{Float64,1}, ::Symbol) at C:\Users\KristofferC\.julia\v0.6\Pardiso\src\Pardiso.jl:183
 [4] solve at C:\Users\KristofferC\.julia\v0.6\Pardiso\src\Pardiso.jl:175 [inlined]
 [5] solve(::Pardiso.PardisoSolver, ::SparseMatrixCSC{Float64,Int64}, ::Array{Float64,1}) at C:\Users\KristofferC\.julia\v0.6\Pardiso\src\Pardiso.jl:174
```

There shouldnt be a problem opening the library, only when you try to solve.

**Comment by donboyd5** [comment]
Interesting. I just got new license, did successful build but get "Wrong username or host name" when trying to solve. Was just about to look for the code that triggers that. I must be doing something wrong in creating license file. Will go back and retrace my steps carefully and retry.

**Comment by KristofferC** [comment]
For Windows you should put your username that you have under `Users`

**Comment by donboyd5** [comment]
Many thanks. I did the following:
- ctrl-alt-delete, clicked Task Manager, looked under Users
- there is only one user, listed as donboyd5@gmail.com(88) - I assumed the (88) does not matter
- so I gave my gmail - email address to Pardiso (which is different from the academic address I use) and they gave me new license by email
- I copied and pasted into pardiso.lic with NOTHING other than that in the file (not even carriage return, although I have tried with and without CR)
- placed it in what I conclude is the home directory: C:\Users\donbo   (although I see that it is only part of my name and part of my username)
- redownloaded Pardiso, extracted to C:\Users\donbo\AppData\Local\JuliaPro-0.5.2.1\pkgs-0.5.2.1\v0.5\Pardiso\deps
- rebooted the computer
- and continued to get the error

I am wondering if the problem is that my username seems to be donboyd5@gmail.com but my user directory is donbo. (I do see that under "Manage Users" I have administrator rights (I am the only one who uses this computer) and that it is password protected (I am pretty sure I know my password but never use it because I use a pin).

I will google around a bit to see if either the username vs directory difference might be the problem but of course if you know off the top of your head I'd really appreciate knowing. Thanks again.

**Comment by KristofferC** [comment]
Your username for the license should be `donbo`.

**Comment by donboyd5** [comment]
Thanks! I will get a new license.

**Comment by donboyd5** [comment]
THANK YOU!  ALL GOOD NOW!

Don

**Comment by KristofferC** [comment]
Nice :)
