### ISSUE TITLE
Pkg.build("PARDISO") - PARDISO 5.0 is not installed

### ISSUE THREAD

**Issue by jipkim** [KristofferC/Pardiso.jl#21]
Hi, I'm having hard time to **install PARDISO package** on Julia.
It would be great if someone can give me some advice.

Here's where I am now.

```
julia> Pkg.build("Pardiso")
INFO: Building Pardiso
did not find libpardiso, assuming PARDISO 5.0 is not installed
found MKLROOT key, using it
```

**My work environment:** 
```
- MacBook Pro (macOS Sierra 10.12.6)
- Processor 2.6 Ghz Intel Core i7
- Memory 16GB 2133 MHz LPDDR3
- Julia 0.6
```

**Pkg.status:**
```
 - Ipopt                         0.2.6
 - JuMP                          0.17.1
 - Pardiso                       0.2.0              7d9a7a35 (dirty)
 - Juno                          0.3.0
```

**Files that I prepared:**
**1) PARDISO 5.0:**  `libpardiso500-MACOS-X86-64.dylib` (http://www.pardiso-project.org/download)
**2) Intel Math Kernel Library for macOS:** `m_mkl_2017.3.181.dmg `(https://software.intel.com/en-us/mkl)

**Terminal Command Result(open -e ~/.bash_profile):**
```
PATH="/Library/Frameworks/Python.framework/Versions/3.6/bin:${PATH}"
export PATH
export LD_LIBRARY_PATH=$LD_LIBRARY_PATH:"/Users/SingingKim/Applications/IBM/ILOG/CPLEX_Studio1271/cplex/bin/x86-64_osx/"
export MKLROOT=“/opt/intel/mkl/bin/“
export PARDISO_PATH=”/Users/SingingKim/.julia/v0.6/Pardiso/deps“
export PATH="/Users/SingingKim/anaconda/bin:$PATH"
```

I've read all the past issues but I couldn't get a right answer for me.
Here's what I want to know.

**1. Where should I put "`libpardiso500-MACOS-X86-64.dylib`" file?**
I currently located it in dir: "`/Users/[Username]/.julia/v0.6/Pardiso/deps`".

**2. Where and how should I set `MKLROOT / PARDISO_PATH` environment variables?**
For now, I've changed .bash_profile as below:
```
export MKLROOT=“/opt/intel/mkl/bin/“
export PARDISO_PATH=”/Users/SingingKim/.julia/v0.6/Pardiso/deps“
```

**3. Should I edit "deps.jl" or "build.jl" in Pardiso directory?**
-If so, where should I add the following expressions?

```
const PARDISO_PATH = ["/Users/SingingKim/.julia/v0.6/Pardiso/deps/"]
@static if is_apple() begin
  const LIBPARDISONAMES = [ "libpardiso500-MACOS-X86-64.dylib" ]

end
```

**4. Where should I put MKL license file that I downloaded from Intel webpage?**

**5. Where should I put Pardiso license key that I obtained from the webpage?**

**Comment by KristofferC** [comment]
It found your MKL installation so you should be able to use `MKLPardisoSolver()`. Does this not work?

**Comment by jipkim** [comment]
Thanks for the quick response. It doesn't work as below.
Before I changed the .bash_profile, it gave me a error message that MKL is not installed.

```
julia> using Pardiso
WARNING: MKL Pardiso did not manage to load, error thrown was: ErrorException("could not load library \"libgomp\"\ndlopen(libgomp.dylib, 9): image not found")
```


```
julia> MKLPardisoSolver()
ERROR: mkl library was not loaded, unable to create solver
Stacktrace:
 [1] Pardiso.MKLPardisoSolver() at /Users/jipkim/.julia/v0.6/Pardiso/src/mkl_pardiso.jl:17

```

**Comment by KristofferC** [comment]
It's failing to load OpenMP. Maybe you can try install that... The reason this package doesn't work so well on Macs is that I have no Mac so I can't really test it :/

**Comment by KristofferC** [comment]
Can you try https://github.com/JuliaSparse/Pardiso.jl/pull/22?

**Comment by jipkim** [comment]
@KristofferC It's working fine now. Thanks a lot! :)
