### ISSUE TITLE
Parallel computing using PardisoSolver()?

### ISSUE THREAD

**Issue by jipkim** [KristofferC/Pardiso.jl#24]
Is it possible to fully utilize all cores while using PardisoSolver()?
My machine uses only 15~18% of CPU load (probably 1 core).

**Comment by KristofferC** [comment]
Did you try https://github.com/JuliaSparse/Pardiso.jl#pardiso-50-1?

I am mostly using the MKL solver and I get maximum usage with that one (tried on a cluster with 20 cores).

**Comment by KristofferC** [comment]
Maybe fixed by https://github.com/JuliaSparse/Pardiso.jl/pull/57?
