### ISSUE TITLE
`libgomp` not loaded if using MKLPardiso in Linux

### ISSUE THREAD

**Issue by photicus** [KristofferC/Pardiso.jl#25]
Simple problem with a simple fix. When I run `Pkg.test("Pardiso")`, I get a failure:

`/opt/julia/bin/julia: symbol lookup error: /opt/intel/mkl/lib/intel64/libmkl_gnu_thread.so: undefined symbol: omp_get_num_procs`

Looks like the line `global const libgomp = Libdl.dlopen("libgomp", Libdl.RTLD_GLOBAL)` is missing at around 
https://github.com/JuliaSparse/Pardiso.jl/blob/f29ec67798a423af87a52517d8cde5d66cf81816/src/Pardiso.jl#L65-L71

It was there in v0.2.0, and now it isn't. Adding that line back fixes the issue - `Pkg.test("Pardiso")` passes.

**Comment by KristofferC** [comment]
Thanks for the report. I will add it back and tag a new version. On my version of MKL, this was apparently not needed.

**Comment by carlomontec** [comment]
I don't know if a current error I have is related, but at least is similar. I am trying to get running Julia+MKLPardiso in a workstation. The Intel MKL tests work for GCC, so I know MKL Pardiso is installed well. From Julia it shows the following error:
```
┌ Error: MKL Pardiso did not manage to load, error thrown was: could not load library "libgomp.so"
│ libgomp.so: cannot open shared object file: No such file or directory

```
with 
```
julia> Pardiso.MKLROOT
"/opt/intel/compilers_and_libraries_2019.4.243/linux/mkl"
```
I have installed Julia 1.1 and the lastest release of Pardiso.jl

**Comment by KristofferC** [comment]
Perhaps `libgomp` need to be present only on some mkl version?

**Comment by photicus** [comment]
I haven't used Pardiso in a while, but I found this to be the case as well. After looking into it a bit, it seems my RHEL workstation (running RHEL 7.5) has version 4.8.5 of `libgomp`, while the code looks for major versions 7 and 8:
https://github.com/JuliaSparse/Pardiso.jl/blob/5d1044311e81c2d0ff451877d90a48f6dce72092/src/Pardiso.jl#L123

What version of  `libgomp` do you have?

**Comment by carlomontec** [comment]
I think @photicus you may be right. This is the current setup:
```
Package: libgomp1
Status: install ok installed
Priority: optional
Section: libs
Installed-Size: 156
Maintainer: Ubuntu Core developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: amd64
Multi-Arch: same
Source: gcc-5
Version: 5.4.0-6ubuntu1~16.04.11
Depends: gcc-5-base (= 5.4.0-6ubuntu1~16.04.11), libc6 (>= 2.17)
Breaks: gcc-4.3 (<< 4.3.6-1), gcc-4.4 (<< 4.4.6-4), gcc-4.5 (<< 4.5.3-2)
Description: GCC OpenMP (GOMP) support library
 GOMP is an implementation of OpenMP for the C, C++, and Fortran compilers
 in the GNU Compiler Collection.
Homepage: http://gcc.gnu.org/
Original-Maintainer: Debian GCC Maintainers <debian-gcc@lists.debian.org>

```
for my personal computer, with GCC 8 and OpenMP8, I have no issues.

**Comment by KristofferC** [comment]
The Pardiso libraries are built for gfortran 7 and 8 I think. Are any of those not installed?
