### ISSUE TITLE
found library but it failed to load due to: libpardiso500-WIN-X86-64.dll

### ISSUE THREAD

**Issue by baermatthias** [KristofferC/Pardiso.jl#27]
- Pardiso libary is in deps folder:
- Working on Windows 10

Pkg.build("Pardiso") yields:

julia> Pkg.build("Pardiso")
INFO: Building Pardiso
found library but it failed to load due to:
could not load library "C:\Users\TEM\ .julia\v0.6\Pardiso\deps\libpardiso500-WIN-X86-64.dll"
�found library but it failed to load due to:
could not load library "libpardiso500-WIN-X86-64.dll"
did not find libpardiso, assuming PARDISO 5.0 is not installed
did not find MKLROOT key, assuming MKL is not installed
WARNING: no Pardiso library managed to load

any suggestions?

Thanks in advance

**Comment by KristofferC** [comment]
What happens if you do `Libdl.dlopen(path, Libdl.RTLD_GLOBAL)` where `path` is the path to the `.dll`?

**Comment by baermatthias** [comment]
It yields:

julia> Libdl.dlopen(path, Libdl.RTLD_GLOBAL)
ERROR: could not load library "C:\Users\TEM\ .julia\v0.6\Pardiso\deps\libpardiso500-WIN-X86-64.dll"
�
Stacktrace:
 [1] dlopen(::String, ::UInt32) at .\libdl.jl:97

I already tried to build Pardiso again with another downloaded version but i still get the same error message.

**Comment by ianwilliamson** [comment]
Is there a solution to this? I am having the same issue.

**Comment by mdrkok** [comment]
I am also experiencing this issue, I though it might have to do with the licence file, but I've done everything they've suggested to fix it - anyone have any ideas?

**Comment by KristofferC** [comment]
I tried it locally now with Windows 10 and v6 of Pardiso and it worked well. So perhaps try again. Closing since this issue is pretty old and might be outdated.
