### ISSUE TITLE
Schur complement calculation

### ISSUE THREAD

**Issue by bdortdivanlioglu** [KristofferC/Pardiso.jl#33]
I would like to get the Schur-complement of the system I am dealing with. It seems we can compute it by using the flag iparm(38). What would be a good way to do so in this package? Thank you.

**Comment by KristofferC** [comment]
It seems that we would need to wrap the `pardiso_get_schur` function.

**Comment by KristofferC** [comment]
Added in https://github.com/JuliaSparse/Pardiso.jl/pull/39
