### ISSUE TITLE
Support for Pardiso 6.0

### ISSUE THREAD

**Issue by ianwilliamson** [KristofferC/Pardiso.jl#34]
I see on pardiso-project.org that Pardiso 6.0 has been released and that the binaries for Pardiso 5.0 are no longer available for download (and apparently now require a license fee?). Should this library be expected to work if the 6.0 binary is dropped in and the appropriate references in the build script are updated?

**Comment by KristofferC** [comment]
It depends if they changed their API. Help testing is greatly appreciated.

**Comment by ianwilliamson** [comment]
It seems that adding the relevant library file name to the list at [build.jl, line 6](https://github.com/JuliaSparse/Pardiso.jl/blob/master/deps/build.jl#L6) does the trick. I successfully ran `Pkg.test("Pardiso")` as well as some computations with my own code.

**Comment by ianwilliamson** [comment]
Note that it doesn't look like they are providing Windows binaries anymore by default, but perhaps you can ask for them if needed. Going forward those instructions in the readme might need to be updated.

**Comment by KristofferC** [comment]
Perhaps we could just search for both v6 (first) and v5 (after).

By the way, did v6 fix anything regarding #31?

**Comment by ianwilliamson** [comment]
Makes sense. Whenever I get a chance, I'll investigate v6.0 in relation to #31

**Comment by KristofferC** [comment]
https://github.com/JuliaSparse/Pardiso.jl/pull/36

**Comment by RoyiAvital** [comment]
They now provide Binaries (`dll` and `lib`) for Windows for PARDISO 6.2.

**Comment by aminya** [comment]
I am confused that the readme says support for Pardiso 5 but this issue is closed

**Comment by KristofferC** [comment]
README was wrong, updated.
