### ISSUE TITLE
ERROR: could not load library "libgfortran" on Ubuntu

### ISSUE THREAD

**Issue by ianwilliamson** [KristofferC/Pardiso.jl#37]
I starting getting this error when calling Pardiso.
```
ERROR: could not load library "libgfortran"
libgfortran.so: cannot open shared object file: No such file or directory
Stacktrace:
 [1] dlopen(::String, ::UInt32) at /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.0/Libdl/src/Libdl.jl:97 (repeats 2 times)
 [2] top-level scope at none:0
```
I'm not sure what exactly caused this but I believe the logic on [line 152](https://github.com/JuliaSparse/Pardiso.jl/blob/637dfc2cf8607f36bc51434054176d401e1d4a99/src/Pardiso.jl#L152) is incorrect. I changed it to
```
gfortran_v = PARDISO_VERSION == 6 ? 7 : 7
```
and the error went away.

**Comment by KristofferC** [comment]
Yeah, we should probably just look through the different gfortran versions. I am not using this package myself much anymore so help is appreciated.

**Comment by KristofferC** [comment]
I think this should be fixed now.
