### ISSUE TITLE
Error in loading libgfortran, from updating to gfortran 9

### ISSUE THREAD

**Issue by wrs28** [KristofferC/Pardiso.jl#41]
I had the same error as in  [#37](https://github.com/JuliaSparse/Pardiso.jl/issues/37), but incremented by one.

By seeding the `main_ver` variable with `8` in [line 152](https://github.com/JuliaSparse/Pardiso.jl/blob/637dfc2cf8607f36bc51434054176d401e1d4a99/src/Pardiso.jl#L152), the search for the gfortran library fails, and therefore loading libgfortran does as well.

Changing the line to `gfortran_v = PARDISO_VERSION == 6 ? 9 : 7` corrects the problem.

What triggered this for me was doing a `brew upgrade`. This updated gcc to 9.1, which is why line 152 breaks. Alternatively, pin brew gcc to version 8.

**Comment by KristofferC** [comment]
Since this is effectively the same as https://github.com/JuliaSparse/Pardiso.jl/issues/37 let's keep the discussion there.
