### ISSUE TITLE
Setting the number of threads

### ISSUE THREAD

**Issue by ZenanH** [KristofferC/Pardiso.jl#45]
I'm using `Pardiso. jl` to solve large sparse equations in the form of Ax = B,A is 420000X420000,B is 420000X1,x is 420000X1,The code is as follows：
```julia
function solve(A,B)
    ps = MKLPardisoSolver()
    set_nprocs!(ps,24)
    result = similar(B)
    result = solve(ps, A, B)
    return result
end
```
1.During the execution of the calculation, I saw that my CPU utilization was about 38%.
2.Time about 43s.
If I comment out `set_nprocs!(ps,24)`,The CPU usage rate and the time spent solving remain unchanged. Why?（By the way, if it's set correctly, is it CP when encountering a large matrix?）

**Comment by ZenanH** [comment]
I noticed that when I started Julia, I typed:
```julia
julia> versioninfo()
Julia Version 1.1.1
Commit 55e36cc308 (2019-05-16 04:10 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Xeon(R) Gold 5118 CPU @ 2.30GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.1 (ORCJIT, skylake)
Environment:
  JULIA_EDITOR = "C:\Users\mg\AppData\Local\atom\app-1.38.2\atom.exe"  -a
  JULIA_NUM_THREADS = 24
```
(Does Pardiso.jl use all threads directly without `set_nprocs!(ps,24)`? )

**Comment by KristofferC** [comment]
The Pardiso setting is supposed to set the threads used for Pardiso in MKL which is completely separate from the number of threads julia uses. I am not sure why it doesn't seem to work here.

**Comment by ZenanH** [comment]
Thank you for your reply. I have the following questions to verify:

- If all the settings are correct (including solving steps and setting the number of threads), when calculating large sparse matrix solution, will the CPU utilization rate be close to 100%? Is this the right way for me to judge execution efficiency by looking at CPU usage?

- On pardiso's official website, there is a [sample file](https://www.pardiso-project.org/manual/exampleunsym.jl) that calculates the real non-symmetric matrix.I am in this situation.There are two solutions used in the file. The first is similar to the code above, and the second is called "incremental steps".
Is there any difference in the efficiency of the two methods?

**Comment by KristofferC** [comment]
They should have the same performance but the incremental steps gives you more control.

**Comment by KristofferC** [comment]
You can look at `get_nprocs(ps)` to see what it says. I don't think there is any bug with the wrapper here.
