### ISSUE TITLE
Uncommitted changes in src/Pardiso.jl ?

### ISSUE THREAD

**Issue by gasagna** [KristofferC/Pardiso.jl#5]
Hi, 
when cloning your repo the file `src/Pardiso.jl` does not appear to get pulled. `git status` shows that that file is modified but not staged for commit.

Or I am missing something?

Thanks

P.S.

I am trying to get this package working under OSX

**Comment by KristofferC** [comment]
I don't believe that is a problem with the repo but more that you have made a local change to `src/Pardiso.jl`. If you want to discard that change you can do `git checkout -- src/Pardiso.jl`.

**Comment by KristofferC** [comment]
Btw, I sort of forgot about this package. I'm better at julia now than when I wrote this so I will look it over and see if some stuff can be improved.

**Comment by gasagna** [comment]
That seems strange. When cloning the repo as `git clone https://github.com/JuliaSparse/Pardiso.jl.git`, the file `src/Pardiso.jl` does not show up in the file manager. Same when downloading a zip file from the front page.

**Comment by KristofferC** [comment]
```
21:00 $ git clone https://github.com/JuliaSparse/Pardiso.jl.git
Cloning into 'Pardiso.jl'...
remote: Counting objects: 235, done.
remote: Total 235 (delta 0), reused 0 (delta 0), pack-reused 235
Receiving objects: 100% (235/235), 45.77 KiB | 0 bytes/s, done.
Resolving deltas: 100% (126/126), done.
Checking connectivity... done.
✔ ~ 
21:00 $ cd Pardiso.jl/
✔ ~/Pardiso.jl [master|✔] 
21:00 $ ls src/
mkl_pardiso.jl  pardiso.jl  Pardiso.jl
✔ ~/Pardiso.jl [master|✔] 
```

**Comment by gasagna** [comment]
```
davide@vega - ~$: git clone https://github.com/JuliaSparse/Pardiso.jl.git
Cloning into 'Pardiso.jl'...
remote: Counting objects: 235, done.
remote: Total 235 (delta 0), reused 0 (delta 0), pack-reused 235
Receiving objects: 100% (235/235), 45.77 KiB | 0 bytes/s, done.
Resolving deltas: 100% (126/126), done.
Checking connectivity... done.
davide@vega - ~$: cd Pardiso.jl
davide@vega - Pardiso.jl$: ls
LICENSE.md  README.md   REQUIRE     src/        test/
davide@vega - Pardiso.jl$: cd src/
davide@vega - src$: ls
mkl_pardiso.jl  pardiso.jl
```

This does not make sense to me. Sorry for the noise....

**Comment by KristofferC** [comment]
Hmm, after seeing that, I would suggest exorcism.

**Comment by gasagna** [comment]
Works OK on another machine.. I just have to do this exorcism now... Will investigate, and close it now. 

Thanks..

**Comment by gasagna** [comment]
This behaviour is due to the OSX filesystem being case independent. When cloning the repo, `src/Pardiso.jl` gets downloaded first and then overwritten by `src/pardiso.jl`, showing uncommited modifications. It can be easily resolved by changing the name of `src/pardiso.jl` to something else.

Nice exorcism...

**Comment by KristofferC** [comment]
Aah! Ok, I will change the name of `pardiso.jl`.

**Comment by gasagna** [comment]
Thanks!
