### ISSUE TITLE
Simplify installation with BinaryBuilder

### ISSUE THREAD

**Issue by ViralBShah** [KristofferC/Pardiso.jl#55]
Is it possible to avoid the wrapper compiler and libgomp linking steps by using MKL and other dependencies from BinaryBuilder?

**Comment by KristofferC** [comment]
There are no compiler or linking steps. The only thing done in the build file is just to look for libpardiso in a couple of places and store a string to the library (https://github.com/JuliaSparse/Pardiso.jl/blob/master/deps/build.jl).

Using MKL_jll might make sense in any case though.
