### ISSUE TITLE
Segfault when OMP_NUM_THREADS > 1

### ISSUE THREAD

**Issue by KristofferC** [KristofferC/Pardiso.jl#7]
``` jl
julia> ENV["OMP_NUM_THREADS"] = 2
2

julia> ps = PardisoSolver()
Pardiso.PardisoSolver:
    Solver: Direct
    Matrix type: Real nonsymmetric
    Phase: Analysis, numerical factorization, solve, iterative refinement
    Num processors: 2

julia> solve(ps, A, B)
*** Error in `/home/kristoffer/julia0.4/julia': double free or corruption (!prev): 0x0000000003b1c9a0 ***

signal (6): Aborted
gsignal at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
abort at /lib/x86_64-linux-gnu/libc.so.6 (unknown line)
unknown function (ip: 0x7f413b4a2394)
unknown function (ip: 0x7f413b4ae66e)
pardiso_ccc_ at /home/kristoffer/julia0.4/usr/bin/../lib/libpardiso.so (unknown line)
pardiso_f_ at /home/kristoffer/julia0.4/usr/bin/../lib/libpardiso.so (unknown line)
pardiso at /home/kristoffer/.julia/v0.4/Pardiso/src/Pardiso.jl:199
solve! at /home/kristoffer/.julia/v0.4/Pardiso/src/Pardiso.jl:171
solve at /home/kristoffer/.julia/v0.4/Pardiso/src/Pardiso.jl:106
julia: malloc.c:3695: _int_malloc: Assertion `(unsigned long) (size) >= (unsigned long) (nb)' failed.
Aborted (core dumped)
```

**Comment by gasagna** [comment]
Same here, on both OSX and linux.  The test .c programs compile and run fine, though.

**Comment by KristofferC** [comment]
I have no idea what the problem is though :(

**Comment by gasagna** [comment]
Not sure I pinpointed the exact reason for this but it seems that setting `ENV["OMP_NUM_THREADS"] = something` from julia is not sufficient. By naively trying a few things, I sort of came up with the conclusion that this enviromental variable must be set in the shell where the julia script gets executed. Also, it seems to me that `iparm[3]` must have a value equal or greater than `OMP_NUM_THREADS`. 

As an alternative, one needs to `import Pardiso` only **after** setting `ENV["OMP_NUM_THREADS"] = something` and not before.

Can you confirm this?

**Comment by KristofferC** [comment]
I set `iparm[3]` to `OMP_NUM_THREADS` when the solver is created: https://github.com/JuliaSparse/Pardiso.jl/blob/1bcad2b58f77101d1745a442a0d29251ba03dbee/src/project_pardiso.jl#L67

Gonna go to gym now but will try what you said afterwards :)

**Comment by KristofferC** [comment]
Cool, no segfault when setting it before loading. I guess that means that it has to be set when `libomp` is loaded. I will document it.
