### ISSUE TITLE
Pardiso.jl v0.5.2 seems to only be compatible with julia >= 1.6

### ISSUE THREAD

**Issue by Pbellive** [KristofferC/Pardiso.jl#81]
After installing Pardiso.jl v0.5.2 on julia 1.5.3 on linux and running `using Pardiso`, I get the following error
```
julia> using Pardiso
[ Info: Precompiling Pardiso [46dd5b70-b6fb-5a00-ae2d-e8fea33afaf2]
ERROR: InitError: TypeError: in ccall: first argument not a pointer or valid constant expression, expected Ptr, got a value of type Tuple{Symbol,String}
Stacktrace:
 [1] get_nprocs_mkl at /home/patrick/julia-dev/Pardiso/src/mkl_pardiso.jl:41 [inlined]
 [2] __init__() at /home/patrick/julia-dev/Pardiso/src/Pardiso.jl:137
 [3] _include_from_serialized(::String, ::Array{Any,1}) at ./loading.jl:697
 [4] _require_from_serialized(::String) at ./loading.jl:749
 [5] _require(::Base.PkgId) at ./loading.jl:1040
 [6] require(::Base.PkgId) at ./loading.jl:928
 [7] require(::Module, ::Symbol) at ./loading.jl:923
during initialization of module Pardiso

```
tested on two x86-64 Ubuntu systems

As far as I can tell, this was caused by the change of the `libmkl_rt` variable from a `String` to a `Ref{String}`. Replacing all the instances of `libmkl_rt[]` with `"libmkl_rt" fixed the problem on the linux machine I tried it on. I realize that's not a real solution to the problem.

Does the `libmkl_rt[]` approach work in 1.6 because of https://github.com/JuliaLang/julia/pull/37123? In any event, unless I'm misunderstanding what's going on here, I think that going forward, either Pardiso.jl should be marked as only compatible with julia 1.6 and up or the next version should be changed to make it backward compatible.

**Comment by KristofferC** [comment]
Yeah, that seems to have been an error on my part. We should probably yank that release and make a new one with the correct compat.
