### ISSUE TITLE
intel mkl seems to be upgraded

### ISSUE THREAD

**Issue by JiangYanLin** [KristofferC/Pardiso.jl#85]
It seems that "intel MKL" is called "intel oneAPI MKL" now and  I can't find any bat file called "mklvars.bat" when I have installed "intel oneAPI MKL"  ,but there is a "setvars.bat" file in the “oneAPI” directory.I use "setvars.bat" instead of "mklvars.bat" .Then I add Pardiso ,  build Pardiso , using Pardiso,and here I crashed ,it logs like 
![log](https://user-images.githubusercontent.com/43395092/144703070-fcefa70c-8521-4fa6-b648-e6d3de09161e.jpg)
The  crashed codes are as follow:
![image](https://user-images.githubusercontent.com/43395092/144703246-ae9fe701-1566-4b61-80ef-5a5a827d792f.png)
i want to know if it is wrong to use "setvars.bat" instead of "mklvars.bat" .

**Comment by ViralBShah** [comment]
Please reopen if still an issue.
