### ISSUE TITLE
Updating README / New naming convention?

### ISSUE THREAD

**Issue by mipals** [KristofferC/Pardiso.jl#98]
Hi again,

I do not really know the customs here in GitHub. Should this be an issue or a discussion? 

As pardiso-project / Pardiso 6 seem to no longer be a thing, many of the naming conventions in both the README and code seem outdated. Before I start changing stuff, it might be a good idea that we agree on a new name. 

On their website it does look like the name that they go for is Panua-Pardiso, so maybe we should stick to that?

![panua-pardiso](https://github.com/JuliaSparse/Pardiso.jl/assets/7252774/a0825821-b6ad-4d8c-8813-e62e009d8ea2)

Cheers,
Mikkel

**Comment by j-fu** [comment]
Hi, I already prepared some modifications regarding panua in the README etc of #75. Still waiting if they will come up with a fix.
Yes, I guess we should refer to it as Panua-Pardiso.

**Comment by KristofferC** [comment]
Makes sense to me.

**Comment by mipals** [comment]
Perfect, lets go with that.

I will have a look at those changes Jürgen. 

In addition, I was not just thinking of changing the README, but also the references in the code, i.e. the build still uses `libpardiso600`, the file called `project_pardiso.jl`, etc. But maybe e.g. the build breaks the code of people using 6.0?

**Comment by j-fu** [comment]
Guess we can close this with #75.
